version: "3"
services:
  frontend:
    image: nginx:alpine
    ports: 
      - "3000:3000"
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./dist:/var/www/html

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.214.0/24
